### ISSUE TITLE
Cannot close hand drawn polygon gate

### ISSUE THREAD

**Issue by Biomiha** [DillonHammill/CytoRSuite#11]
I'm following the workflow in the vignette using the fcs files in this project: 
https://flowrepository.org/id/FR-FCM-ZZ36. 
If I try to draw a manual gate I'm never able to close the polygon. I suppose there'd need to be a margin when the clicks are close enough to close the polygon gate. 
I hope the screenshot conveys the issue better than words. 
![screenshot 2019-02-17 at 09 29 11](https://user-images.githubusercontent.com/29175188/52910940-85a24c00-3296-11e9-9b30-6e1d5ca9b82d.png)

**Comment by DillonHammill** [comment]
Details for specific gate types can be found in the Introduction section of the gating functions vignette:

https://dillonhammill.github.io/CytoRSuite/articles/CytoRSuite-Gating-Functions.html

I will summarise these details below:
 - `polygon` gate - requires minimum 3 points which can be sealed by right click and selecting stop. This is the only gate type which requires the "stop" to close the gate. All other gates have expected inputs.
 - `rectangle` gate - requires selection of 2 diagonal points.
 - `boundary` gate - requires selection of the upper bound of the population (1 point).
 - `threshold` gate - requires selection of the lower bound of the population (1 point).
 - `interval` gate - requires selection of lower and upper bound of the population (2 points).
 - `ellipse` gate - requires selection of lower and upper bounds in 2 dimensions (4 points total).
 - `quadrant` gates - requires the selection of the center of the crosshair (1 point).
 - `web` gates - requires the selection of the center of the crosshair as well as the protruding arms. This is modified version of the quadrant gate which allows fine tuning of arm angles.

For more details refer to the vignette which includes videos for all gate types.

To use a different gate type in `gate_draw` simply supply the type of gate to the `type` argument. 

```{r}
gate_draw(gs,
          parent = "root",
          alias = "Cells",
          channels = c("FSC-A","SSC-A"),
          gatingTemplate = "Example-gatingTemplate.csv",
          type = "polygon")
```
