### ISSUE TITLE
Compute spillover matrix for mixed unstained/stained beads/cells

### ISSUE THREAD

**Issue by DillonHammill** [DillonHammill/CytoRSuite#18]
@DillonHammill   First, what a great contribution. Kudos.  

I'm still working through things, and despite your answer to this issue, I'm still stuck on whether/how you can do spillover correction if you have a combination of bead standards (stained/unstained bead mixture) for some channels and cell stains for other channels (stain only).   The universal unstained cells would not seem to be appropriate for use in this case, although admittedly, I'm still working through the mechanics going on under the hood..

Any way to do this or sample code available?

_Originally posted by @rwbaer in https://github.com/DillonHammill/CytoRSuite/issues/16#issuecomment-495238674_

**Comment by DillonHammill** [comment]
Hi @rwbaer,

Thank you for trying the package! Unfortunately this feature is not yet supported but will be incorporated in the new release of v1.0.0 which should be complete soon.

Once support has been added I will update this issue with the appropriate workflow.

**Comment by DillonHammill** [comment]
Here is something you can do in the meantime @rwbaer.

If you have mixed stained beads with unstained beads you do in fact have a universal unstained control that you just need to pull out so that it can be used as the reference population for `spillover_compute()`. See workflow below using `flowCore` style subsetting to pull out the unstained population and write it to  a new .fcs file:

```{r}
library(CytoRSuite)

# Load in compensation controls into flowSet
files <- list.files(path = "Name of folder containing samples", full.names = TRUE)
fs <- read.ncdfFlowSet(files = files)

# Add fs to GatingSet
gs <- GatingSet(fs)

# Transform fluorescent channels so that we can gate out the positive signal
fluor_channels <- cyto_fluor_channels(gs)
trans <- estimateLogicle(gs[[1]], fluor_channels)
gs <- transform(gs, trans)

# Gate controls to home in on single beads
# Cells -
gate_draw(gs,
parent = "root",
alias = "Beads",
channels = c("FSC-A","SSC-A"),
gatingTemplate = "Compensation-gatingTemplate.csv")

# Single Cells -
gate_draw(gs,
parent = "Beads",
alias = "Single Beads",
channels = c("FSC-A","FSC-H"),
gatingTemplate = "Compensation-gatingTemplate.csv")

# Next we will extract the data for one of the controls (choose the one with the best separation)
fr <- getData(gs, "Single Cells")[[1]]

# Next we will construct a gate `gt` around the positive signal
gt <- gate_draw(fr, 
alias = "stained",
channels = "PE-A",  # Use the name of the channel associated with this control
type = "interval")

# Next we will get the events outside this gate (our unstained events) using `split`
unst <- split(fr, gt[[1]])[[2]]

# Inverse the transformations to get data on linear scale again
inv <- transformList(names(trans), lapply(trans, `[[`, "inverse"))
unst <- transform(unst, inv)

# Write unstained data to new .fcs file which can be used as the unstained control
write.FCS(unst, "Unstained-Control.fcs")
```

Now that you have the unstained events as a .fcs file you can add this to the folder containing your other samples, load in the samples, re-apply the gatingTemplate and pass these samples to `spillover_compute()`.

Hope this helps!
Dillon

**Comment by rwbaer** [comment]
Thanks for the suggestion. I will give it a try.  

The beauty of working with data using packages like yours is you can learn so much about the underlying assum[tions you are making.  Thanks for taking the time to make the suggestion.

**Comment by DillonHammill** [comment]
@rwbaer, this feature is now supported in CytoExploreR!

Simply don't select `Unstained` from the dropdown menu and you will be asked to gate the negative and positive populations within each compensation control.
