### ISSUE TITLE
Installation error due CytoRSuiteData name change

### ISSUE THREAD

**Issue by jonasmac16** [DillonHammill/CytoRSuite#19]
Hi,
I tried to install `CytoRSuite` with the vignettes today and it failed due to missing the `CytoRSuiteData` library. I guess the recent name change of that package has caused that issue.

Best
Jonas

**Comment by DillonHammill** [comment]
Hi jonas,

Sorry about that, I am making major updates to CytoRSuite and CytoRSuiteData over the next couple of weeks. I have reverted the pull request which has caused this error.  I will re-merge it when everything is ready.

You should be able to install CytoRSuiteData again now:

```{r}
library(devtools)
install_github("DillonHammill/CytoRSuiteData", ref = "master")
```

Dillon

**Comment by DillonHammill** [comment]
Works fine on my end, can you try again now?

**Comment by DillonHammill** [comment]
The extra printouts are the depreciation warnings from the recent openCyto/flowWorkspace API name changes (if you have newer versions installed). I will be pushing the required updates when I update the entire package over the next couple of weeks. Everything should still work as expected.

**Comment by jonasmac16** [comment]
@MartinMestdagh Installing `CytoRSuiteData` works fine following the installation instructions, however it is being installed as `CytoRSuiteExploreData` since your recent PR. That name change in turn seemed to have caused the building of vignettes in `CytoRSuite` to fail because it still looking for `CytoRSuiteData` rather than `CytoRSuiteExploreData`.

Hence installing `CytoRSuite`like this: `devtools::install_github("DillonHammill/CytoRSuite", build_vignettes = FALSE)` works fine.

**Comment by DillonHammill** [comment]
This should be fine for now as all the vignettes are on the website. I will try and remove this from the README.

**Comment by jonasmac16** [comment]
Thanks. BTW just started using it but really enjoying`CytoRSuite`. Nice job.

**Comment by DillonHammill** [comment]
Wait until you see what's coming :)
