### ISSUE TITLE
cyto_plot plots positive gate of mindensity rather than negative gate

### ISSUE THREAD

**Issue by jonasmac16** [DillonHammill/CytoRSuite#21]
Hi,
I am trying to plot an automated negative gate create by `mindensity`, but I when plotting it via `cyto_plot` it plot the positive gate. Is this a known issue how can I solve it.

Thanks

**Comment by DillonHammill** [comment]
Hi @jonasmac16,

This is implemented in the new release coming next week.

Dillon

**Comment by jonasmac16** [comment]
Great,looking forward to it. In the mean while is there a quick hack?

**Comment by DillonHammill** [comment]
What kind of plot are you trying to generate? Could you post an example here?

**Comment by DillonHammill** [comment]
One way would be to convert the gate to one which defines that population and pass it through the gate argument of cyto_plot().

```{r}
# Live Cells (negated population) gs (GatingSet)
gate <- gs_pop_get_gate(gs, "Live Cells")[[1]]

# Pull out gate coords
gate_coords <- c(gate@min, gate@max)

# Modify coords - inverse Inf coord
gate_coords <- c(-Inf, gate_coords[1])

# Construct new gate
gate_coords <- matrix(gate_coords, ncol = 1)
colnames(gate_coords) <- parameters(gate)
rownames(gate_coords) <- c("min","max")
gate <- rectangleGate(.gate = gate_coords, filterId = "Live Cells")

# Plot using cyto_plot
cyto_plot(gs,
          parent = "Cells",
          channels = parameters(gate),
          gate = gate)
```

That should do the trick for now, but you will still run into problems with `cyto_plot_gating_scheme()` as it does not accept gate objects.

Dillon

**Comment by DillonHammill** [comment]
Alternatively you can use `gate_edit()` to replace this gate with a manual one. In which case everything will work as expected.

**Comment by DillonHammill** [comment]
@jonasmac16, this feature is now implemented in CytoExploreR!
