### ISSUE TITLE
404 error on link for Windows installation instructions

### ISSUE THREAD

**Issue by davinap** [DillonHammill/CytoRSuite#23]
At the bottom of this page (https://github.com/DillonHammill/CytoRSuite), there are instructions on how to install CytoRSuite however, the link for the Windows users does not work and produces a 404 error. Please attach the correct link for the installation instructions. 
Thanks!

**Comment by DillonHammill** [comment]
@davinap, this package is no longer under development. Please use CytoExploreR instead https://dillonhammill.github.io/CytoExploreR/.
